%YAML:1.0
---
Image.IndexFile: "/home/echo/cvdesign/FaceRecognition/faces_database/database.csv"

# if false, values from Eigen.ReducedModel will be used instead
Eigen.Recompute: true
# Required for Eigen.Recompute == true
Eigen.RequiredSize: 200
# Required for Eigen.Recompute == false
Eigen.FullModel: "/home/echo/cvdesign/FaceRecognition/eigen_models/eigen_full.yaml"
Eigen.ReducedModel: "/home/echo/cvdesign/FaceRecognition/eigen_models/eigen.yaml"

Output.Directory: "."
Output.EigenfacesModel: "/home/echo/cvdesign/FaceRecognition/eigenfaces_models/eigenfaces_050418.yaml"
Output.FullModel: "./eigen_full_new.yaml"
Output.ReducedModel: "./eigen_new.yaml"